"""SU(2) lattice/graph gauge re-anchoring helpers.

Convention
----------
A directed link U[i, j] is interpreted as transport / transition from site i to
site j. Local gauge transformations act as

    U[i, j] -> H[i]^-1 U[i, j] H[j]

where H[i] is an SU(2) matrix and inverse means conjugate transpose.

For a pure gauge generated by site frames G[i],

    U[i, j] = G[i]^-1 G[j].

Her re-anchoring on a triangle (i, j, k) predicts

    U[j, k] = U[i, j]^-1 U[i, k].

The triangle residual is

    R[i, j, k] = U[i, j]^-1 U[i, k] U[j, k]^-1.

Perfect consistency gives R = I. Under local SU(2) gauge transformations,
this residual transforms covariantly by conjugation at the j endpoint:

    R'[i, j, k] = H[j]^-1 R[i, j, k] H[j].

Therefore the matrix residual is not generally invariant. Gauge-invariant
quantities include conjugacy invariants such as trace(R), Frobenius distance
from identity, and eigenvalues / rotation angle.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence

import numpy as np

Array = np.ndarray

I2 = np.eye(2, dtype=complex)
SIGMA_X = np.array([[0, 1], [1, 0]], dtype=complex)
SIGMA_Y = np.array([[0, -1j], [1j, 0]], dtype=complex)
SIGMA_Z = np.array([[1, 0], [0, -1]], dtype=complex)
PAULI = np.array([SIGMA_X, SIGMA_Y, SIGMA_Z])


@dataclass(frozen=True)
class MatrixResidualSummary:
    """Summary statistics for matrix-valued triangle residuals."""

    n_sites: int
    n_triangles: int
    max_frobenius_error: float
    mean_frobenius_error: float
    max_rotation_angle: float
    mean_rotation_angle: float
    max_unitarity_error: float
    max_det_error: float


def dagger(A: Array) -> Array:
    """Conjugate transpose of a matrix or stack of matrices."""

    return np.swapaxes(np.conjugate(A), -1, -2)


def inverse_su2(U: Array) -> Array:
    """Inverse for SU(2) matrices, equal to conjugate transpose."""

    return dagger(U)


def su2_from_quaternion(q: Sequence[float]) -> Array:
    """Build an SU(2) matrix from a real unit quaternion q=(a,b,c,d).

    The representation used is

        [[ a + i b,  c + i d],
         [-c + i d,  a - i b]].
    """

    q_arr = np.asarray(q, dtype=float)
    norm = float(np.linalg.norm(q_arr))
    if norm == 0.0:
        raise ValueError("Cannot build SU(2) matrix from zero quaternion.")
    a, b, c, d = q_arr / norm
    return np.array(
        [[a + 1j * b, c + 1j * d], [-c + 1j * d, a - 1j * b]],
        dtype=complex,
    )


def random_su2(seed: int | None = None, rng: np.random.Generator | None = None) -> Array:
    """Draw a random SU(2) matrix from a normalized Gaussian quaternion."""

    if rng is None:
        rng = np.random.default_rng(seed)
    q = rng.normal(size=4)
    return su2_from_quaternion(q)


def random_su2_stack(n: int, seed: int | None = None) -> Array:
    """Return n random SU(2) matrices."""

    rng = np.random.default_rng(seed)
    return np.array([random_su2(rng=rng) for _ in range(n)])


def su2_axis_angle(axis: Sequence[float], angle: float) -> Array:
    """Build SU(2) rotation exp(i angle/2 * axis dot sigma).

    The angle is the associated SO(3)-style rotation angle. In SU(2), +/-I
    both appear as central elements, so the returned diagnostic angle should be
    interpreted carefully near pi.
    """

    axis_arr = np.asarray(axis, dtype=float)
    norm = float(np.linalg.norm(axis_arr))
    if norm == 0.0:
        raise ValueError("Rotation axis must be nonzero.")
    n = axis_arr / norm
    generator = n[0] * SIGMA_X + n[1] * SIGMA_Y + n[2] * SIGMA_Z
    return np.cos(angle / 2.0) * I2 + 1j * np.sin(angle / 2.0) * generator


def random_small_su2(strength: float, rng: np.random.Generator) -> tuple[Array, float, Array]:
    """Return a random SU(2) perturbation, angle, and axis."""

    axis = rng.normal(size=3)
    axis = axis / np.linalg.norm(axis)
    angle = float(rng.uniform(-strength, strength))
    return su2_axis_angle(axis, angle), angle, axis


def pure_gauge_links(frames: Array) -> Array:
    """Build complete directed SU(2) pure-gauge links from site frames.

    U[i, j] = G[i]^-1 G[j].
    """

    G = np.asarray(frames, dtype=complex)
    n = G.shape[0]
    U = np.empty((n, n, 2, 2), dtype=complex)
    G_inv = inverse_su2(G)
    for i in range(n):
        for j in range(n):
            U[i, j] = G_inv[i] @ G[j]
    return U


def random_pure_gauge(n_sites: int, seed: int | None = None) -> tuple[Array, Array]:
    """Return (site_frames, links) for a random SU(2) pure gauge field."""

    frames = random_su2_stack(n_sites, seed=seed)
    return frames, pure_gauge_links(frames)


def random_reciprocal_links(n_sites: int, seed: int | None = None) -> Array:
    """Random reciprocal complete directed SU(2) links, generally not pure gauge.

    Enforces U[j, i] = U[i, j]^-1 and U[i, i] = I, but not triangle
    consistency. This is a synthetic non-flat/inconsistent field.
    """

    rng = np.random.default_rng(seed)
    U = np.empty((n_sites, n_sites, 2, 2), dtype=complex)
    for i in range(n_sites):
        U[i, i] = I2
    for i in range(n_sites):
        for j in range(i + 1, n_sites):
            M = random_su2(rng=rng)
            U[i, j] = M
            U[j, i] = inverse_su2(M)
    return U


def gauge_transform(U: Array, H: Array) -> Array:
    """Apply local SU(2) gauge transformation U_ij -> H_i^-1 U_ij H_j."""

    U_arr = np.asarray(U, dtype=complex)
    H_arr = np.asarray(H, dtype=complex)
    n = U_arr.shape[0]
    V = np.empty_like(U_arr)
    H_inv = inverse_su2(H_arr)
    for i in range(n):
        for j in range(n):
            V[i, j] = H_inv[i] @ U_arr[i, j] @ H_arr[j]
    return V


def triangle_indices(n_sites: int, ordered: bool = True) -> list[tuple[int, int, int]]:
    """Generate triangle triples with distinct indices."""

    triples: list[tuple[int, int, int]] = []
    if ordered:
        for i in range(n_sites):
            for j in range(n_sites):
                if j == i:
                    continue
                for k in range(n_sites):
                    if k == i or k == j:
                        continue
                    triples.append((i, j, k))
    else:
        for i in range(n_sites):
            for j in range(i + 1, n_sites):
                for k in range(j + 1, n_sites):
                    triples.append((i, j, k))
    return triples


def reanchored_link(U: Array, i: int, j: int, k: int) -> Array:
    """Predict U[j, k] from U[i, j] and U[i, k]."""

    return inverse_su2(U[i, j]) @ U[i, k]


def triangle_residual(U: Array, i: int, j: int, k: int) -> Array:
    """Residual R = U_ij^-1 U_ik U_jk^-1. Perfect consistency gives I."""

    return reanchored_link(U, i, j, k) @ inverse_su2(U[j, k])


def triangle_residuals(U: Array, ordered: bool = True) -> tuple[list[tuple[int, int, int]], Array]:
    """Return triangle triples and residual matrices."""

    n = U.shape[0]
    triples = triangle_indices(n, ordered=ordered)
    residuals = np.array([triangle_residual(U, i, j, k) for i, j, k in triples])
    return triples, residuals


def frobenius_errors(residuals: Array) -> Array:
    """Frobenius norm ||R - I|| for each residual."""

    return np.linalg.norm(residuals - I2, axis=(-2, -1))


def su2_rotation_angles(residuals: Array) -> Array:
    """Conjugacy-invariant SU(2) rotation angle in [0, pi].

    For SU(2), trace(U) = 2 cos(theta/2) for matrices generated as
    exp(i theta/2 n.sigma). Near the identity, arccos magnifies tiny trace
    roundoff, so residuals already Frobenius-close to I are reported as zero.
    """

    R = np.asarray(residuals, dtype=complex)
    tr = np.real(np.trace(R, axis1=-2, axis2=-1)) / 2.0
    tr = np.clip(tr, -1.0, 1.0)
    theta = 2.0 * np.arccos(tr)
    theta = np.minimum(theta, 2.0 * np.pi - theta)
    close_to_identity = frobenius_errors(R) < 1e-12
    return np.where(close_to_identity, 0.0, theta)


def unitarity_errors(mats: Array) -> Array:
    """Return ||U^dagger U - I||_F for each matrix."""

    return np.linalg.norm(dagger(mats) @ mats - I2, axis=(-2, -1))


def det_errors(mats: Array) -> Array:
    """Return |det(U) - 1| for each matrix."""

    return np.abs(np.linalg.det(mats) - 1.0)


def residual_summary(U: Array, ordered: bool = True) -> MatrixResidualSummary:
    """Compute summary stats for all SU(2) triangle residuals."""

    triples, R = triangle_residuals(U, ordered=ordered)
    fro = frobenius_errors(R)
    angles = su2_rotation_angles(R)
    return MatrixResidualSummary(
        n_sites=int(U.shape[0]),
        n_triangles=len(triples),
        max_frobenius_error=float(np.max(fro)) if fro.size else 0.0,
        mean_frobenius_error=float(np.mean(fro)) if fro.size else 0.0,
        max_rotation_angle=float(np.max(angles)) if angles.size else 0.0,
        mean_rotation_angle=float(np.mean(angles)) if angles.size else 0.0,
        max_unitarity_error=float(np.max(unitarity_errors(R))) if len(triples) else 0.0,
        max_det_error=float(np.max(det_errors(R))) if len(triples) else 0.0,
    )


def residual_covariance_error(U: Array, H: Array, ordered: bool = True) -> float:
    """Max error in R' = H[j]^-1 R H[j] across triangle residuals."""

    triples, R = triangle_residuals(U, ordered=ordered)
    V = gauge_transform(U, H)
    _, R2 = triangle_residuals(V, ordered=ordered)
    H_inv = inverse_su2(H)
    errs = []
    for idx, (_, j, _) in enumerate(triples):
        predicted = H_inv[j] @ R[idx] @ H[j]
        errs.append(np.linalg.norm(R2[idx] - predicted))
    return float(np.max(errs)) if errs else 0.0


def residual_literal_change(U: Array, H: Array, ordered: bool = True) -> float:
    """Max literal matrix change ||R' - R|| under gauge transformation.

    This is expected to be nonzero for a generic non-Abelian residual. It is
    included to prevent accidentally treating SU(2) like U(1).
    """

    _, R = triangle_residuals(U, ordered=ordered)
    V = gauge_transform(U, H)
    _, R2 = triangle_residuals(V, ordered=ordered)
    errs = np.linalg.norm(R2 - R, axis=(-2, -1))
    return float(np.max(errs)) if errs.size else 0.0


def residual_trace_invariance_error(U: Array, H: Array, ordered: bool = True) -> float:
    """Max |tr(R') - tr(R)| under local gauge transformations."""

    _, R = triangle_residuals(U, ordered=ordered)
    V = gauge_transform(U, H)
    _, R2 = triangle_residuals(V, ordered=ordered)
    return float(np.max(np.abs(np.trace(R2, axis1=-2, axis2=-1) - np.trace(R, axis1=-2, axis2=-1))))


def reanchored_link_covariance_error(U: Array, H: Array, ordered: bool = True) -> float:
    """Check that U_ij^-1 U_ik transforms as a j->k link."""

    triples = triangle_indices(U.shape[0], ordered=ordered)
    V = gauge_transform(U, H)
    H_inv = inverse_su2(H)
    errs = []
    for i, j, k in triples:
        P = reanchored_link(U, i, j, k)
        P2 = reanchored_link(V, i, j, k)
        predicted = H_inv[j] @ P @ H[k]
        errs.append(np.linalg.norm(P2 - predicted))
    return float(np.max(errs)) if errs else 0.0


def perturb_links(
    U: Array,
    edges: Iterable[tuple[int, int]],
    strength: float = 0.6,
    seed: int | None = None,
    reciprocal: bool = True,
    side: str = "right",
) -> tuple[Array, dict[tuple[int, int], dict[str, object]]]:
    """Multiply selected links by random SU(2) perturbations.

    Parameters
    ----------
    U:
        Link tensor with shape (n, n, 2, 2).
    edges:
        Directed edges to perturb.
    strength:
        Maximum absolute rotation angle for each perturbation.
    seed:
        Random seed.
    reciprocal:
        If True, set U[j, i] = U[i, j]^-1 after perturbing U[i, j].
    side:
        "right" applies U[i,j] <- U[i,j] P. "left" applies U[i,j] <- P U[i,j].
    """

    rng = np.random.default_rng(seed)
    V = np.array(U, dtype=complex, copy=True)
    metadata: dict[tuple[int, int], dict[str, object]] = {}
    n = V.shape[0]
    if side not in {"right", "left"}:
        raise ValueError("side must be 'right' or 'left'.")
    for i, j in edges:
        if i == j:
            raise ValueError("Self-links should not be perturbed.")
        if not (0 <= i < n and 0 <= j < n):
            raise IndexError(f"Edge {(i, j)} outside link matrix of size {n}.")
        P, angle, axis = random_small_su2(strength=strength, rng=rng)
        if side == "right":
            V[i, j] = V[i, j] @ P
        else:
            V[i, j] = P @ V[i, j]
        metadata[(i, j)] = {"angle": angle, "axis": axis.tolist(), "side": side}
        if reciprocal:
            V[j, i] = inverse_su2(V[i, j])
    return V, metadata


def edge_key(i: int, j: int) -> tuple[int, int]:
    """Canonical undirected edge key for reciprocal link corruption scoring."""

    return (i, j) if i < j else (j, i)


def residual_participation_scores(U: Array, ordered: bool = True) -> dict[tuple[int, int], float]:
    """Score links by sum of SU(2) residual rotation angles touching the edge."""

    triples, R = triangle_residuals(U, ordered=ordered)
    errors = su2_rotation_angles(R)
    scores: dict[tuple[int, int], float] = {}
    for (i, j, k), err in zip(triples, errors):
        for a, b in ((i, j), (i, k), (j, k)):
            key = edge_key(a, b)
            scores[key] = scores.get(key, 0.0) + float(err)
    return scores


def top_scored_edges(scores: dict[tuple[int, int], float], m: int) -> list[tuple[tuple[int, int], float]]:
    """Return top-m edges by descending score."""

    return sorted(scores.items(), key=lambda item: item[1], reverse=True)[:m]
