"""U(1) lattice/graph gauge re-anchoring helpers.

Convention
----------
Sites carry local phases h_i = exp(i lambda_i). Directed link variables
are written U[i, j], interpreted as transport / transition from site i to
site j, with gauge action

    U[i, j] -> conj(h_i) * U[i, j] * h_j.

For a pure gauge field generated by site phases alpha_i,

    U[i, j] = exp(i * (alpha_j - alpha_i)).

Her re-anchoring on a triangle (i, j, k) predicts

    U[j, k] = inv(U[i, j]) * U[i, k].

The triangle residual is

    R[i, j, k] = inv(U[i, j]) * U[i, k] * inv(U[j, k]).

For U(1), inv(z) = conj(z) for unit phases. A perfect residual is 1.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence

import numpy as np

Array = np.ndarray


@dataclass(frozen=True)
class ResidualSummary:
    """Summary statistics for triangle residuals."""

    n_sites: int
    n_triangles: int
    max_chord_error: float
    mean_chord_error: float
    max_angle_error: float
    mean_angle_error: float


def as_u1(angle: Array | float) -> Array | complex:
    """Return exp(i angle)."""

    return np.exp(1j * angle)


def inverse_u1(z: Array | complex) -> Array | complex:
    """Inverse for unit complex phases."""

    return np.conjugate(z)


def normalize_u1(z: Array) -> Array:
    """Project nonzero complex values onto U(1)."""

    mag = np.abs(z)
    if np.any(mag == 0):
        raise ValueError("Cannot normalize zero complex values to U(1).")
    return z / mag


def pure_gauge_links(alpha: Sequence[float]) -> Array:
    """Build complete directed U(1) pure-gauge links from site phases.

    U[i, j] = exp(i * (alpha[j] - alpha[i]))
    """

    a = np.asarray(alpha, dtype=float)
    return as_u1(a[None, :] - a[:, None])


def random_site_phases(n_sites: int, seed: int | None = None) -> Array:
    """Random site phases in [0, 2pi)."""

    rng = np.random.default_rng(seed)
    return rng.uniform(0.0, 2.0 * np.pi, size=n_sites)


def random_pure_gauge(n_sites: int, seed: int | None = None) -> tuple[Array, Array]:
    """Return (alpha, U) for a random U(1) pure gauge field."""

    alpha = random_site_phases(n_sites, seed=seed)
    return alpha, pure_gauge_links(alpha)


def random_reciprocal_links(n_sites: int, seed: int | None = None) -> Array:
    """Random reciprocal complete directed U(1) links, generally not pure gauge.

    Enforces U[j, i] = inv(U[i, j]) and U[i, i] = 1, but does not enforce
    triangle consistency. This is a useful synthetic non-flat/inconsistent field.
    """

    rng = np.random.default_rng(seed)
    U = np.ones((n_sites, n_sites), dtype=complex)
    for i in range(n_sites):
        for j in range(i + 1, n_sites):
            z = as_u1(rng.uniform(-np.pi, np.pi))
            U[i, j] = z
            U[j, i] = inverse_u1(z)
    return U


def perturb_links(
    U: Array,
    edges: Iterable[tuple[int, int]],
    strength: float = 0.5,
    seed: int | None = None,
    reciprocal: bool = True,
) -> tuple[Array, dict[tuple[int, int], float]]:
    """Multiply selected directed links by random U(1) phase errors.

    Parameters
    ----------
    U:
        Link matrix.
    edges:
        Directed edges to perturb.
    strength:
        Maximum absolute angle perturbation in radians.
    seed:
        Random seed.
    reciprocal:
        If True, perturb U[j, i] by the inverse phase so reciprocal structure
        U[j, i] = inv(U[i, j]) remains true.

    Returns
    -------
    U_new, perturbation_angles_by_edge
    """

    rng = np.random.default_rng(seed)
    V = np.array(U, dtype=complex, copy=True)
    deltas: dict[tuple[int, int], float] = {}
    n = V.shape[0]
    for i, j in edges:
        if i == j:
            raise ValueError("Self-links should not be perturbed.")
        if not (0 <= i < n and 0 <= j < n):
            raise IndexError(f"Edge {(i, j)} outside link matrix of size {n}.")
        delta = float(rng.uniform(-strength, strength))
        phase = as_u1(delta)
        V[i, j] *= phase
        deltas[(i, j)] = delta
        if reciprocal:
            V[j, i] = inverse_u1(V[i, j])
    return V, deltas


def gauge_transform(U: Array, lambdas: Sequence[float]) -> Array:
    """Apply U(1) local gauge transformation U_ij -> h_i^-1 U_ij h_j."""

    h = as_u1(np.asarray(lambdas, dtype=float))
    return inverse_u1(h)[:, None] * U * h[None, :]


def triangle_indices(n_sites: int, ordered: bool = True) -> list[tuple[int, int, int]]:
    """Generate triangle triples with distinct indices.

    ordered=True returns all ordered triples i, j, k with distinct indices.
    ordered=False returns i < j < k only.
    """

    triples: list[tuple[int, int, int]] = []
    if ordered:
        for i in range(n_sites):
            for j in range(n_sites):
                if j == i:
                    continue
                for k in range(n_sites):
                    if k == i or k == j:
                        continue
                    triples.append((i, j, k))
    else:
        for i in range(n_sites):
            for j in range(i + 1, n_sites):
                for k in range(j + 1, n_sites):
                    triples.append((i, j, k))
    return triples


def reanchored_link(U: Array, i: int, j: int, k: int) -> complex:
    """Predict U[j, k] from U[i, j] and U[i, k]."""

    return inverse_u1(U[i, j]) * U[i, k]


def triangle_residual(U: Array, i: int, j: int, k: int) -> complex:
    """Residual R = U_ij^-1 U_ik U_jk^-1. Perfect consistency gives R=1."""

    return reanchored_link(U, i, j, k) * inverse_u1(U[j, k])


def triangle_residuals(U: Array, ordered: bool = True) -> tuple[list[tuple[int, int, int]], Array]:
    """Return triangle triples and residual complex phases."""

    n = U.shape[0]
    triples = triangle_indices(n, ordered=ordered)
    residuals = np.array([triangle_residual(U, i, j, k) for i, j, k in triples])
    return triples, residuals


def chord_errors(residuals: Array) -> Array:
    """Chord error |R - 1| on the unit circle."""

    return np.abs(residuals - 1.0)


def angle_errors(residuals: Array) -> Array:
    """Absolute wrapped phase error |arg(R)| in radians."""

    return np.abs(np.angle(residuals))


def residual_summary(U: Array, ordered: bool = True) -> ResidualSummary:
    """Compute summary stats for all triangle residuals."""

    triples, R = triangle_residuals(U, ordered=ordered)
    chord = chord_errors(R)
    angle = angle_errors(R)
    return ResidualSummary(
        n_sites=int(U.shape[0]),
        n_triangles=len(triples),
        max_chord_error=float(np.max(chord)) if chord.size else 0.0,
        mean_chord_error=float(np.mean(chord)) if chord.size else 0.0,
        max_angle_error=float(np.max(angle)) if angle.size else 0.0,
        mean_angle_error=float(np.mean(angle)) if angle.size else 0.0,
    )


def gauge_residual_covariance_error(
    U: Array,
    lambdas: Sequence[float],
    ordered: bool = True,
) -> float:
    """For U(1), triangle residuals should be gauge-invariant.

    Returns max |R'(i,j,k) - R(i,j,k)| over all selected triangles.
    In a non-Abelian group the corresponding statement would be covariance by
    conjugation at the middle/target source endpoint, not scalar invariance.
    """

    triples, R = triangle_residuals(U, ordered=ordered)
    V = gauge_transform(U, lambdas)
    _, R2 = triangle_residuals(V, ordered=ordered)
    return float(np.max(np.abs(R2 - R))) if len(triples) else 0.0


def edge_key(i: int, j: int) -> tuple[int, int]:
    """Canonical undirected edge key for scoring reciprocal link corruption."""

    return (i, j) if i < j else (j, i)


def residual_participation_scores(U: Array, ordered: bool = True) -> dict[tuple[int, int], float]:
    """Score links by sum of triangle residual angle errors touching the edge.

    For reciprocal U(1) link corruption, use canonical undirected edge keys.
    """

    triples, R = triangle_residuals(U, ordered=ordered)
    errors = angle_errors(R)
    scores: dict[tuple[int, int], float] = {}
    for (i, j, k), err in zip(triples, errors):
        for a, b in ((i, j), (i, k), (j, k)):
            key = edge_key(a, b)
            scores[key] = scores.get(key, 0.0) + float(err)
    return scores


def top_scored_edges(scores: dict[tuple[int, int], float], m: int) -> list[tuple[tuple[int, int], float]]:
    """Return top-m edges by descending score."""

    return sorted(scores.items(), key=lambda item: item[1], reverse=True)[:m]
